### ISSUE TITLE
Need to build a reset method?

### ISSUE THREAD

**Issue by MengZn** [kubespray/kubespray-cli#107]
I used the kubespray-cli to build the Kubernetes environment, and also thought of using kubespray-cli to remove the Kubernetes environment created by kubespray-cli.

**Comment by MengZn** [comment]
This is my first  test environment : ubuntu 16.04 & Kubernetes v1.7.3+coreos.0
include three nodes which are three master nodes and two worker nodes.

**Comment by Smana** [comment]
Thank you @MengZn, that was indeed missing.
I'll test your pr https://github.com/kubespray/kubespray-cli/pull/106 asap

**Comment by MengZn** [comment]
@Smana Should I provide detail info of my test environment ?
