### ISSUE TITLE
(note) kargo-cli Docker image fails with an Ansible setuptools dependency issue

### ISSUE THREAD

**Issue by jalbstmeijer** [kubespray/kubespray-cli#58]
Not really a kargo-cli bug, but maybe an idea to include a fixed tested version of Ansible in the Docker image?

Quick fix, run in Docker shell: pip install distribute --upgrade --force

https://github.com/ansible/ansible/issues/16015

**Comment by Smana** [comment]
Thank you @jalbstmeijer i'll add that asap

**Comment by Smana** [comment]
Actually the docker image is not updated. i've dropped its support.
Please install it with `pip` and eventually create your own image
